mime_types:
  image:
    - image/jpeg
    - image/tiff
    - image/png
    - image/gif
  video:
    - video/mp4
extensions:
  image:
    - tif
    - jpg
    - tiff
    - jpeg
    - png
    - gif
    - jp2
  video:
    - mp4