mime_types:
  iiif_image:
    - image/jpeg
    - image/tiff
  image:
    - image/png
  video:
    - video/mp4
extensions:
  iiif_image:
    - tif
    - jpg
  image:
    - tiff
    - jpeg
    - png
    - gif
    - jp2
  video:
    - mp4