development:
  server: http://localhost:3000
  #'cfs' staging file config. Note that this doesn't strictly need to be a dx/cfs file system,
  #but we use that name in order to distinguish from our internal bit file stuff for now.
  cfs:
    root: /Users/hding2/repos/medusa-collection-registry/tmp/storage-dev/root
    tmp: /Users/hding2/repos/medusa-collection-registry/tmp
    fits_home: /Users/hding2/src/fits
    export_root: /Users/hding2/repos/medusa-collection-registry/tmp/storage-dev/export-root
    export_autoclean: false
  #staging directory information
  staging_storage:
    #an array of hashes which have the local_path (i.e. as the medusa server sees it) and the remote_path
    #what will be recorded in the external file path)
    roots:
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/dev-1
        remote_path: /dev-staging-root-1
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/dev-2
        remote_path: /dev-staging-root-2
  accrual_storage:
    #an array of hashes which have the local_path (i.e. as the medusa server sees it) and the remote_path
    #what will be recorded in the external file path)
    roots:
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/dev-1
        remote_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/dev-1
        name: staging-1
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/dev-2
        remote_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/dev-2
        name: staging-2
  #This opens a few actions to basic auth so that machine clients can use them
  basic_auth: machine_user:machine_password
  medusa_users_group: Library Medusa Users
  medusa_admins_group: Library Medusa Admins
  amazon:
    outgoing_queue: medusa_to_glacier_dev
    incoming_queue: glacier_to_medusa_dev
  fixity_server:
    outgoing_queue: medusa_to_fixity_dev
    incoming_queue: fixity_to_medusa_dev
  amqp:
    #FOR LOCAL USE
    port: 5672
    #FOR USE WITH TEST SERVER
#    ssl: true
#    host: rabbitmq-dev.library.illinois.edu
#    user: medusa
#    password: cestUmTi
#    vhost: medusa-test
#    verify_peer: false
  iiif: &IIIF_DEV
    host: localhost
    port: 43001
    root: iiif
  public_view_on: false
  email:
    feedback: hding2@illinois.edu
    dev: hding2@illinois.edu
    noreply: medusa-noreply@medusatest.library.illinois.edu
    admin: hding2@illinois.edu
  fits_batch_size: 1000
  fits_server_url: http://localhost:4567
  fits_storage: /Users/hding2/repos/medusa-collection-registry/tmp/storage-dev/fits
  ldap:
    host: ad.uillinois.edu
    port: 389
    protocol: tls
    user: CN=IDEALSLookup,OU=SU Accounts,OU=Library,OU=Urbana,DC=ad,DC=uillinois,DC=edu
    passwd: "@-?Refactoring7@-?"
    base: DC=ad,DC=uillinois,DC=edu
    search: ^CN=([^,]+),((CN|OU)=[^,]+,)*DC=ad,DC=uillinois,DC=edu$

test:
  server: http://localhost:3000
  cfs:
    root: /Users/hding2/repos/medusa-collection-registry/tmp/storage-test/root
    tmp: /Users/hding2/repos/medusa-collection-registry/tmp
    fits_home: /Users/hding2/src/fits
    export_root: /Users/hding2/repos/medusa-collection-registry/tmp/storage-test/export-root
    export_autoclean: false
  staging_storage:
    roots:
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/test-1
        remote_path: /test-staging-root-1
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/test-2
        remote_path: /test-staging-root-2
  accrual_storage:
    roots:
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/test-1
        remote_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/test-1
        name: staging-1
      - local_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/test-2
        remote_path: /Users/hding2/repos/medusa-collection-registry/tmp/staging-roots/test-1
        name: staging-2
  #the tests assume the following
  basic_auth: machine_user:machine_password
  medusa_users_group: Library Medusa Users
  medusa_admins_group: Library Medusa Admins
  amazon:
    outgoing_queue: medusa_to_glacier_test
    incoming_queue: glacier_to_medusa_test
  fixity_server:
    outgoing_queue: medusa_to_fixity_test
    incoming_queue: fixity_to_medusa_test
  iiif: &IIIF_TEST
    host: localhost
    port: 43002
    root: iiif
    #disabled: true
  public_view_on: true
  #Some tests may assume the following
  email:
    feedback: medusa-feedback@example.com
    dev: medusa-dev@example.com
    noreply: medusa-noreply@example.com
    admin: medusa-admin@example.com
  fits_batch_size: 1000
  fits_server_url: http://localhost:4567
  fits_storage: /Users/hding2/repos/medusa-collection-registry/tmp/storage-dev/fits
production:
  server: http://localhost:3000
  basic_auth: change_this_user:change_this_password
  medusa_users_group: Library Medusa Users
  medusa_admins_group: Library Medusa Admins
  public_view_on: true
