#For the loading to work correctly the base key has to be the class where Eventable is included.
#So for STI like file group we can't have different events available for each type; it has to be the base class here
file_group:
  external_delete:
    message: Delete external file group
    normal_event_key: external_deleted
  external_to_bit:
    message: Ingest staged file group to bit-level store
    normal_event_key: staged_to_bit
  external_to_object:
    message: Ingest staged file group to object-level store
    normal_event_key: staged_to_object
