#This controls how files are previewed
cfs_file_viewers:
  mime_types:
    image:
      - image/jpeg
      - image/tiff
      - image/png
      - image/gif
    video:
      - video/mp4
  extensions:
    image:
      - tif
      - jpg
      - tiff
      - jpeg
      - png
      - gif
      - jp2
    video:
      - mp4
#The following are config for specific classes, using the convention classes.<class_name>.<setting_name>
classes:
  assessment:
    assessment_types:
      - external_files
    risk_levels:
      - low
      - medium
      - high
      - urgent
  file_group:
    acquisition_methods:
      - internal digitization
      - vendor digitization
      - electronic records acquisition
      - external deposit
  fits_data:
    simple_string_fields:
      :file_format: fits/identification/identity/@format
      :file_format_version: fits/identification/identity/version
      :mime_type: fits/identification/identity/@mimetype
      :pronom_id: fits/identification/identity/externalIdentifier[@type="puid"]
      :file_size: fits/fileinfo/size
      :creating_application: fits/fileinfo/creatingApplicationName
      :well_formed: fits/filestatus/well-formed
      :is_valid: fits/filestatus/valid
      :message: fits/filestatus/message
      :audio_bit_depth: fits/metadata/audio/bitDepth
      :audio_byte_order: fits/metadata/audio/byteOrder
      :audio_data_encoding: fits/metadata/audio/audioDataEncoding
      :audio_sample_rate: fits/metadata/audio/sampleRate
      :document_protection: fits/metadata/document/isProtected
      :document_rights_management: fits/metadata/document/isRightsManaged
      :image_bits_per_sample: fits/metadata/image/bitsPerSample
      :image_byte_order: fits/metadata/image/byteOrder
      :image_color_space: fits/metadata/image/colorSpace
      :image_compression_scheme: fits/metadata/image/compressionScheme
      :text_character_set: fits/metadata/text/charset
      :text_markup_basis: fits/metadata/text/markupBasis
      :text_markup_basis_version: fits/metadata/text/markupBasisVersion
      :video_bit_depth: fits/metadata/video/bitDepth
      :video_compressor: fits/metadata/video/videoCompressor
      :video_compression_scheme: fits/metadata/video/compressionScheme
      :video_sample_rate: fits/metadata/video/sampleRate
    date_fields:
      :last_modified_date: fits/fileinfo/lastmodified
      :creation_date: fits/fileinfo/created
  item:
    source_media_types:
      - DVD
      - Floppy Disk
      - Hard Disk
    equipment_types:
      - BC100
      - RCAM
      - Canon Sheetfed
      - Epson Flatbed
    statuses:
      - Sent to Conservation
      - Sent to Preservation
      - Sent to IPM
      - Sent for cataloging
      - Send to IA for digitization
#These are events available to the various eventables as a hash from stored string to descriptive string
#For the loading to work correctly the base key has to be the class where Eventable is included.
#So for STI like file group we can't have different events available for each type; it has to be the base class here
events:
  file_group:
    created: File group created
    external_staged: External file group staged
    staged_to_bit: Staged files ingested to bit-level store
    staged_deleted: Staged files deleted
    staged_modified: Staged file group modified
    external_deleted: External file group deleted
    fits_performed: FITS analysis performed
    cfs_fits_performed: FITS analysis performed on CFS root
    bit_exported: Bit-level file group exported
    bit_deleted: Bit-level file group deleted
    files_added: Accrual to existing file group
    amazon_backup_part_completed: Part of Amazon Glacier backup completed
    amazon_backup_completed: Amazon Glacier backup completed
    fixity_check_scheduled: Fixity check scheduled
    fixity_check_completed: Fixity check completed
  cfs_directory:
    fixity_check_scheduled: Fixity check scheduled
    fixity_check_completed: Fixity check completed
    deposit_completed: Deposit completed
  cfs_file:
    fixity_check_run: Fixity check run
    fixity_result: Fixity result


